import NavBar from "@/components/Shared/NavBar";
import "./globals.css";
import Footer from "@/components/Shared/Footer";

export const metadata = {
  title: "Watch Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <NavBar></NavBar>
        <div>{children}</div>
        <Footer></Footer>
      </body>
    </html>
  );
}
